services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: zelthy
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_NAME: postgres
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
    ports:
      - "8000:8000"
    command: >
      sh -c "sleep 5 &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"